---
- name: Check Windows Server Specs
  hosts: LT-433
  gather_facts: yes
  tasks:

    - name: Display Hostname
      ansible.builtin.debug:
        var: ansible_hostname

    - name: Display Operating System Version
      ansible.builtin.debug:
        var: ansible_distribution_version

    - name: Check total physical memory
      win_shell: |
        $totalMemory = Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty TotalPhysicalMemory
        Write-Output $totalMemory
      register: memory_info

    - name: Show total physical memory
      ansible.builtin.debug:
        msg: "Total Physical Memory: {{ (memory_info.stdout|int / (1024*1024) ) | round(2) }} MB"

    - name: Check disk usage
      win_shell: |
        Get-PSDrive -PSProvider FileSystem | Select-Object Used,Free,@{Name='PercentUsed';Expression={[math]::round(($_.Used/($_.Used+$_Free))*100,2)}}
      register: disk_usage

    - name: Show disk usage
      ansible.builtin.debug:
        msg: "{{ item.MountRoot }}: {{ item.PercentUsed }}% used"
      loop: "{{ disk_usage.stdout_lines }}"
      vars:
        mount_root_index: 0
        percent_used_index: 2
      when: item != ""

    - name: Check CPU architecture
      win_shell: |
        $arch = Get-WmiObject Win32_Processor | Select-Object -ExpandProperty Architecture
        Write-Output $arch
      register: cpu_architecture

    - name: Show CPU architecture
      ansible.builtin.debug:
        msg: "CPU Architecture: {{ 'x86' if cpu_architecture.stdout.strip() == '0' else 'x64' if cpu_architecture.stdout.strip() == '9' else 'Unknown'}}"
