- name: Install Amolto manually on Windows 11
  hosts: windows
  gather_facts: yes
  become: true
  tasks:
    - name: Download Amolto installer
      win_get_url:
        url: "https://www.amolto.com/downloads/Amolto_Call_Recorder_Setup.exe"
        dest: "C:\\temp\\Amolto_Call_Recorder_Setup.exe"

    - name: Install Amolto
      win_command: "C:\\temp\\Amolto_Call_Recorder_Setup.exe /silent"
