---
- name: Install TightVNC using Chocolatey
  hosts: windows
  gather_facts: yes
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey_facts:

    - name: Install TightVNC using Chocolatey
      win_chocolatey:
        name: tightvnc
        state: present
