---
- name: Install OpenVPN Connect using Chocolatey on Windows 11
  hosts: windows
  gather_facts: yes
  become: true  # Ensure we run as an administrator
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey_facts:

    - name: Install OpenVPN Connect using Chocolatey
      win_chocolatey:
        name: OpenVPN Connect
        state: present
