---
- name: Install Google Chrome on Windows 11
  hosts: windows
  gather_facts: yes
  become: true
  tasks:
    - name: Install Google Chrome via Chocolatey
      win_chocolatey:
        name: googlechrome
        state: present
