---
- name: Install Bitwarden for Google Chrome on Windows 11
  hosts: windows
  gather_facts: yes
  become: true  # Ensure we run as an administrator
  tasks:
    - name: Install Google Chrome via Chocolatey (if not installed)
      win_chocolatey:
        name: googlechrome
        state: present

    - name: Install Bitwarden Chrome extension via Chocolatey
      win_chocolatey:
        name: bitwarden-chrome
        state: present
