---
- name: Install Amolto manually on Windows 11
  hosts: windows
  gather_facts: yes
  become: true
  tasks:
    - name: Download Amolto installer
      win_get_url:
        url: "https://amolto.com/files/AmoltoCallRecorder.msi"
        dest: "C:\\temp\\AmoltoCallRecorder.msi"

    - name: Install Amolto using msiexec
      win_command: "msiexec /i C:\\temp\\AmoltoCallRecorder.msi /quiet /norestart"
