---
- name: Install WinRAR using Chocolatey on Windows 11
  hosts: windows
  gather_facts: yes
  become: true  # Ensure we run as an administrator
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey_facts:

    - name: Install WinRAR using Chocolatey
      win_chocolatey:
        name: winrar
        state: present
