---
- name: Install OpenVPN Connect on Windows
  hosts: windows
  gather_facts: no
  tasks:

    - name: Download OpenVPN Connect installer
      win_get_url:
        url: https://swupdate.openvpn.net/downloads/OpenVPN-Connect-v3-windows.msi
        dest: C:\Temp\OpenVPN-Connect.msi

    - name: Install OpenVPN Connect
      win_shell: |
        msiexec /i C:\Temp\OpenVPN-Connect.msi /quiet /norestart
      args:
        executable: powershell

    - name: Remove OpenVPN Connect installer
      win_file:
        path: C:\Temp\OpenVPN-Connect.msi
        state: absent
