---
- name: Install Bitwarden for Google Chrome on Windows 11
  hosts: windows
  gather_facts: yes
  become: true
  tasks:
    - name: Install Google Chrome via Chocolatey (if not installed)
      win_chocolatey:
        name: googlechrome
        state: present
        source: 'https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi'
        ignore_checksums: true
