---
- name: Install Google Chrome and Bitwarden extension for Chrome
  hosts: windows
  gather_facts: yes
  become: true  # Run as administrator
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey_facts:

    - name: Install Google Chrome using Chocolatey
      win_chocolatey:
        name: googlechrome
        state: present

    - name: Install Bitwarden for Chrome via Chocolatey
      win_chocolatey:
        name: bitwarden-chrome
        state: present
