---
- name: Uninstall WinRAR on Windows 11
  hosts: windows  # The target host/group in your inventory
  become: true    # Run as administrator
  tasks:
    - name: Uninstall WinRAR via Chocolatey
      win_chocolatey:
        name: winrar
        state: absent
