---
- name: Install or update Skype using Chocolatey on Windows 11
  hosts: windows
  gather_facts: yes
  become: true  # Ensure we run as an administrator
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey_facts:

    - name: Install Skype manually using custom URL
      win_get_url:
        url: https://go.skype.com/skype.download/Skype-8.136.0.202.msi
        dest: C:\Temp\Skype-Installer.msi

    - name: Install Skype from MSI
      win_package:
        path: C:\Temp\Skype-Installer.msi
        state: present
        product_id: 'Skype'
